# Generated by Django 5.2.4 on 2025-10-16 20:36

from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('erpdb', '0001_initial'),
    ]

    operations = [
        # Add new fields to PurchaseOrder
        migrations.AddField(
            model_name='purchaseorder',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),

        # Add new fields to PurchaseOrderItem
        migrations.AddField(
            model_name='purchaseorderitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),

        # Add new fields to Payment
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_generated',
            field=models.BooleanField(default=False),
        ),

        # Remove payment_terms from PurchaseOrder if it exists
        # migrations.RemoveField(
        #     model_name='purchaseorder',
        #     name='payment_terms',
        # ),
    ]
