# Generated by Django 5.2.4 on 2025-10-16 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpdb', '0002_auto_20251017_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='tax_rate',
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erpdb.warehouse'),
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
