# Generated by Django 5.2.4 on 2025-10-12 16:54

from django.db import migrations, models


def add_fields_if_not_exist(apps, schema_editor):
    """Add fields only if they don't already exist in the database."""
    with schema_editor.connection.cursor() as cursor:
        # Check if received_quantity exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='erpdb_purchaseorderitem' 
            AND column_name='received_quantity'
        """)
        received_quantity_exists = cursor.fetchone() is not None

        # Check if tax_rate exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='erpdb_purchaseorderitem' 
            AND column_name='tax_rate'
        """)
        tax_rate_exists = cursor.fetchone() is not None

        # Add received_quantity if it doesn't exist
        if not received_quantity_exists:
            cursor.execute("""
                ALTER TABLE erpdb_purchaseorderitem 
                ADD COLUMN received_quantity INTEGER DEFAULT 0 NOT NULL
            """)

        # Add tax_rate if it doesn't exist
        if not tax_rate_exists:
            cursor.execute("""
                ALTER TABLE erpdb_purchaseorderitem 
                ADD COLUMN tax_rate NUMERIC(5, 2) DEFAULT 0 NOT NULL
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('erpdb', '0006_add_invoice_to_payment'),
    ]

    operations = [
        # Use RunPython to conditionally add fields
        migrations.RunPython(add_fields_if_not_exist, reverse_code=migrations.RunPython.noop),

        # Update status choices for PurchaseOrder (this is safe to run multiple times)
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('received', 'Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
