# Generated by Django 5.2.4 on 2025-10-12 16:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpdb', '0004_alter_category_options_alter_warehouse_options_and_more'),
    ]

    operations = [
        # Add missing fields to PurchaseOrderItem
        migrations.AddField(
            model_name='purchaseorderitem',
            name='received_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        # Update status choices for PurchaseOrder
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('received', 'Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
