# Generated by Django 5.2.4 on 2025-10-12 17:16

from django.db import migrations


def add_created_at_if_not_exist(apps, schema_editor):
    """Add created_at field only if it doesn't already exist in the database."""
    with schema_editor.connection.cursor() as cursor:
        # Check if created_at exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='erpdb_purchaseorder' 
            AND column_name='created_at'
        """)
        created_at_exists = cursor.fetchone() is not None

        # Add created_at if it doesn't exist
        if not created_at_exists:
            cursor.execute("""
                ALTER TABLE erpdb_purchaseorder 
                ADD COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('erpdb', '0005_sync_purchase_order_model'),
    ]

    operations = [
        # Use RunPython to conditionally add field
        migrations.RunPython(add_created_at_if_not_exist, reverse_code=migrations.RunPython.noop),
    ]
