# Generated by Django 5.2.4 on 2025-10-12 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpdb', '0005_sync_purchase_order_model'),
    ]

    operations = [
        # Add created_at field with a default value for existing rows
        migrations.AddField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
