# Generated by Django 5.2.4 on 2025-10-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erpdb', '0006_fix_purchase_order_created_at'),
    ]

    operations = [
        # This migration is empty because all the fields are already in the database
        # and the model changes have been handled by previous migrations
    ]
