# Generated by Django 5.2.4 on 2025-10-12 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erpdb', '0007_finalize_purchase_order_fields'),
    ]

    operations = [
        # Handle field renames and additions for PurchaseOrder
        # Note: These fields may already be renamed in the database, so we use state_operations only
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='expected_delivery',
            new_name='delivery_date',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='order_number',
            new_name='po_number',
        ),
        # Add missing fields if they don't exist
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name = 'erpdb_purchaseorder' 
                              AND column_name = 'payment_terms') THEN
                    ALTER TABLE erpdb_purchaseorder ADD COLUMN payment_terms VARCHAR(100);
                END IF;
            END $$;
            """,
            reverse_sql="ALTER TABLE erpdb_purchaseorder DROP COLUMN IF EXISTS payment_terms;",
            state_operations=[
                migrations.AddField(
                    model_name='purchaseorder',
                    name='payment_terms',
                    field=models.CharField(blank=True, max_length=100, null=True),
                ),
            ]
        ),
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name = 'erpdb_purchaseorder' 
                              AND column_name = 'reference_number') THEN
                    ALTER TABLE erpdb_purchaseorder ADD COLUMN reference_number VARCHAR(50);
                END IF;
            END $$;
            """,
            reverse_sql="ALTER TABLE erpdb_purchaseorder DROP COLUMN IF EXISTS reference_number;",
            state_operations=[
                migrations.AddField(
                    model_name='purchaseorder',
                    name='reference_number',
                    field=models.CharField(blank=True, max_length=50, null=True),
                ),
            ]
        ),
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name = 'erpdb_purchaseorder' 
                              AND column_name = 'warehouse_id') THEN
                    ALTER TABLE erpdb_purchaseorder ADD COLUMN warehouse_id BIGINT;
                    ALTER TABLE erpdb_purchaseorder ADD CONSTRAINT erpdb_purchaseorder_warehouse_id_fkey 
                    FOREIGN KEY (warehouse_id) REFERENCES erpdb_warehouse(id);
                END IF;
            END $$;
            """,
            reverse_sql="ALTER TABLE erpdb_purchaseorder DROP COLUMN IF EXISTS warehouse_id;",
            state_operations=[
                migrations.AddField(
                    model_name='purchaseorder',
                    name='warehouse',
                    field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erpdb.warehouse'),
                    preserve_default=False,
                ),
            ]
        ),
        # Handle PurchaseOrderItem changes
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name = 'erpdb_purchaseorderitem' 
                              AND column_name = 'received_quantity') THEN
                    ALTER TABLE erpdb_purchaseorderitem ADD COLUMN received_quantity INTEGER DEFAULT 0;
                END IF;
            END $$;
            """,
            reverse_sql="ALTER TABLE erpdb_purchaseorderitem DROP COLUMN IF EXISTS received_quantity;",
            state_operations=[
                migrations.AddField(
                    model_name='purchaseorderitem',
                    name='received_quantity',
                    field=models.IntegerField(default=0),
                ),
            ]
        ),
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name = 'erpdb_purchaseorderitem' 
                              AND column_name = 'tax_rate') THEN
                    ALTER TABLE erpdb_purchaseorderitem ADD COLUMN tax_rate DECIMAL(5,2) DEFAULT 0;
                END IF;
            END $$;
            """,
            reverse_sql="ALTER TABLE erpdb_purchaseorderitem DROP COLUMN IF EXISTS tax_rate;",
            state_operations=[
                migrations.AddField(
                    model_name='purchaseorderitem',
                    name='tax_rate',
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ]
        ),
        # Update status choices
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('received', 'Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
