# Generated by Django 5.2.4 on 2025-10-12 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erpdb', '0009_final_schema_sync'),
    ]

    operations = [
        # This is a placeholder migration to mark all model changes as applied
        # The database schema is already correct and matches the models
    ]
