# Generated by Django 5.2.4 on 2025-10-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erpdb', '0010_complete_sync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='line_total',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='unit_cost',
        ),
    ]
