# Generated by Django 5.2.4 on 2025-10-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erpdb', '0010_complete_sync'),
    ]

    operations = [
        # Conditionally remove fields only if they exist
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.columns 
                          WHERE table_name = 'erpdb_purchaseorderitem' 
                          AND column_name = 'line_total') THEN
                    ALTER TABLE erpdb_purchaseorderitem DROP COLUMN line_total;
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.columns 
                          WHERE table_name = 'erpdb_purchaseorderitem' 
                          AND column_name = 'unit_cost') THEN
                    ALTER TABLE erpdb_purchaseorderitem DROP COLUMN unit_cost;
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
